import {BROWSERS, BROWSER_VERSIONS, OSS, OS_VERSIONS, WINDOW_SIZES, TEST_TYPES, TEST_PRIORITIES} from './supported-capabilities'

export const FILTER_PARAMS = {
  BROWSERS: 'browsers',
  BROWSER_VERSIONS: 'browserVersions',
  OSS: 'OSs',
  OS_VERSIONS: 'osVersions',
  PRIORITIES: 'priorities',
  TYPES: 'types',
  WINDOW_SIZES: 'windowSizes',
  IDS: 'IDs'
}
export const MAP_FILTER_PARAM_TO_SUPPORTED = {
  [FILTER_PARAMS.WINDOW_SIZES]: WINDOW_SIZES,
  [FILTER_PARAMS.BROWSERS]: BROWSERS,
  [FILTER_PARAMS.BROWSER_VERSIONS]: BROWSER_VERSIONS,
  [FILTER_PARAMS.OSS]: OSS,
  [FILTER_PARAMS.OS_VERSIONS]: OS_VERSIONS,
  [FILTER_PARAMS.TYPES]: TEST_TYPES,
  [FILTER_PARAMS.PRIORITIES]: TEST_PRIORITIES
}
