// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
  'aws_app_analytics': 'enable',
  'aws_cognito_identity_pool_id': 'eu-central-1:cd7f16fa-e338-41a5-8c5d-74d612c1977d',
  'aws_cognito_region': 'eu-central-1',
  'aws_content_delivery': 'enable',
  'aws_content_delivery_bucket': 'prioritybook-hosting-mobilehub-1639782335',
  'aws_content_delivery_bucket_region': 'eu-central-1',
  'aws_content_delivery_cloudfront': 'enable',
  'aws_content_delivery_cloudfront_domain': 'd12pdamgwznsyo.cloudfront.net',
  'aws_mobile_analytics_app_id': 'e6d305cdaa754654afd9b673b6c19d49',
  'aws_mobile_analytics_app_region': 'us-east-1',
  'aws_project_id': 'ecb77e80-d819-4965-970e-f99ef4a67d24',
  'aws_project_name': 'Priority Book',
  'aws_project_region': 'eu-central-1',
  'aws_resource_name_prefix': 'prioritybook-mobilehub-1639782335'
}

export default awsmobile
